# HW04 (제출기한-4월21일23시)
Datascience 모듈의 Table 연습을 위한 문제입니다. 
- 반드시 수업시간 배운 내용만을 사용하여 코드를 작성합니다. 
- 한 셀에 여러줄의 코드를 사용해도 무방합니다.

제출시 다음 사항에 유의하기 바랍니다.
- 텍스트 셀에 설명되어 있는 각 문항을 잘 읽은 뒤,
- 코드 셀에 적절한 코드를 작성하기 바랍니다.
- 작성 후 파일명에 ``학번``을 명시후 지정한 공유폴더에 업로드합니다.
- 이때, 공유를 반드시 profkwon@cicweb.ulsan.ac.kr 에게만 합니다.

In [0]:
from datascience import *
import numpy as np

In [29]:
movie = Table.read_table('top_movies.csv')
movie

Title                                     | Studio               | Gross     | Gross (Adjusted) | Year
Star Wars: The Force Awakens              | Buena Vista (Disney) | 906723418 | 906723400        | 2015
Avatar                                    | Fox                  | 760507625 | 846120800        | 2009
Titanic                                   | Paramount            | 658672302 | 1178627900       | 1997
Jurassic World                            | Universal            | 652270625 | 687728000        | 2015
Marvel's The Avengers                     | Buena Vista (Disney) | 623357910 | 668866600        | 2012
The Dark Knight                           | Warner Bros.         | 534858444 | 647761600        | 2008
Star Wars: Episode I - The Phantom Menace | Fox                  | 474544677 | 785715000        | 1999
Star Wars                                 | Fox                  | 460998007 | 1549640500       | 1977
Avengers: Age of Ultron                   | Buena Vista (Disney) | 459005868 | 465684200        | 2015
The Dark Knight Rises                     | Warner Bros.         | 448139099 | 500961700        | 2012
... (190 rows omitted)

### 문제1
'Gross (Adjusted)' label을 'Adjusted Gross'로 변경하여 movie변수에 assignment하시오.

In [0]:
movie = Table.read_table('top_movies.csv').relabeled(3, 'Adjusted Gross')

In [31]:
movie

Title                                     | Studio               | Gross     | Adjusted Gross | Year
Star Wars: The Force Awakens              | Buena Vista (Disney) | 906723418 | 906723400      | 2015
Avatar                                    | Fox                  | 760507625 | 846120800      | 2009
Titanic                                   | Paramount            | 658672302 | 1178627900     | 1997
Jurassic World                            | Universal            | 652270625 | 687728000      | 2015
Marvel's The Avengers                     | Buena Vista (Disney) | 623357910 | 668866600      | 2012
The Dark Knight                           | Warner Bros.         | 534858444 | 647761600      | 2008
Star Wars: Episode I - The Phantom Menace | Fox                  | 474544677 | 785715000      | 1999
Star Wars                                 | Fox                  | 460998007 | 1549640500     | 1977
Avengers: Age of Ultron                   | Buena Vista (Disney) | 459005868 | 465684200      | 2015
The Dark Knight Rises                     | Warner Bros.         | 448139099 | 500961700      | 2012
... (190 rows omitted)

### 문제2
Adjusted Gross의 최소값을 구하여 min_adjgross 변수에 저장하시오.

In [0]:
min_adjgross = movie.column('Adjusted Gross').min()

In [33]:
min_adjgross

322261900

### 문제3
min_adjgross 대비 각 영화의 Adjusted Gross  비율을 구하여 'Ratio'라는 이름의 column을 movie Table에 추가하여 assign하시오.

In [0]:
movie = movie.with_columns('Ratio', movie.column('Adjusted Gross')/min_adjgross)

In [35]:
movie.show(3)

### 문제4
Paramount 제작 영화만을 출력하시오.

In [36]:
movie.where('Studio', 'Paramount')

Title                                              | Studio    | Gross     | Adjusted Gross | Year | Ratio
Titanic                                            | Paramount | 658672302 | 1178627900     | 1997 | 3.65736
Forrest Gump                                       | Paramount | 330252182 | 683929300      | 1994 | 2.12228
Iron Man                                           | Paramount | 318412101 | 385808100      | 2008 | 1.19719
Indiana Jones and the Kingdom of the Crystal Skull | Paramount | 317101119 | 384231200      | 2008 | 1.19229
Iron Man 2                                         | Paramount | 312433331 | 341908200      | 2010 | 1.06096
Raiders of the Lost Ark                            | Paramount | 248159971 | 770183000      | 1981 | 2.38993
Beverly Hills Cop                                  | Paramount | 234760478 | 584205200      | 1984 | 1.81283
Ghost                                              | Paramount | 217631306 | 447747400      | 1990 | 1.38939
Mission: Impossible II                             | Paramount | 215409889 | 347693200      | 2000 | 1.07892
Indiana Jones and the Last Crusade                 | Paramount | 197171806 | 429923500      | 1989 | 1.33408
... (15 rows omitted)

### 문제5
Adjusted Gross가 가장 높았던 Top 10을 출력하시오.

In [37]:
movie.sort('Adjusted Gross', descending=True).show(10)

### 문제6
Paramount 제작 영화 중 Adjusted Gross가 가장 높았던 Top 10을 출력하시오.

In [38]:
movie.where('Studio', 'Paramount').sort('Adjusted Gross', descending=True).show(10)

### 문제7
2000년대 영화들 중 Ratio가 2.0이상인 영화들을 Ratio가 높은 순으로 출력하시오.

In [39]:
movie.where('Year', are.above_or_equal_to(2000)).where('Ratio', are.above_or_equal_to(2.0)).sort('Ratio', descending=True).show()

### 문제8
a와 b를 입력받아 Year가 a이상이고 Ratio가 b이상인 영화의 편수를 리턴하는 함수인 count_movies 함수를 작성하시오.
(Hint: Table()객체에는 num_rows와 num_columns라는 속성값을 통해 행과 열의 개수를 각각 표현한다.)

예) print(movie.num_rows)

In [0]:
def count_movies(a,b):
  result = movie.where('Year', are.above_or_equal_to(a)).where('Ratio', are.above_or_equal_to(b)).num_rows
  
  return result

In [41]:
count_movies(2000, 2.0)

5

### 보너스문제
위 데이터에 대하여 본인이 출제하고 싶은 문제가 있으면 한 문제를 출제하고 아래에 답안 코드를 작성하시오.

a, b, c를 입력받아 Year가 a이상 b이하에 있고 Ratio값이 c 이상인 영화의 Title을 리턴하는 함수인 whatis_return 함수를 작성하시오.

In [0]:
def whatis_return(a,b,c):
  result = movie.where('Year', are.between_or_equal_to(a,b)).where('Ratio', are.above_or_equal_to(c)).select('Title')
  
  return result

In [43]:
whatis_return(1999,2019,2.0)

Title
Star Wars: The Force Awakens
Avatar
Jurassic World
Marvel's The Avengers
The Dark Knight
Star Wars: Episode I - The Phantom Menace